password = ""  
username = "" 
term = "" # For example for courses in Fall 2023 or Winter 2024 term will be 202301 and 202302 respectively

[[courses]] 
crn = "98133" # Course CRN on self service
number = "2600" # subject name for COMP
subject = "BUSI" # Course number for example 4304

[[courses]] 
crn = "98322"
number = "4304"
subject = "COMP"
